export const fruits = [
  { id: 1, name: "Apple", description: "A red fruit" },
  { id: 2, name: "Banana", description: "A yellow fruit" },
  { id: 3, name: "Orange", description: "A orange fruit" },
  { id: 4, name: "Grapes", description: "A purple fruit" },
  { id: 5, name: "Pineapple", description: "A yellow fruit" },
  { id: 6, name: "Watermelon", description: "A green fruit" },
  { id: 7, name: "Mango", description: "A yellow fruit" },
  { id: 8, name: "Papaya", description: "A orange fruit" },
  { id: 9, name: "Strawberry", description: "A red fruit" },
  { id: 10, name: "Pomegranate", description: "A red fruit" },
  { id: 11, name: "Guava", description: "A green fruit" },
  { id: 12, name: "Kiwi", description: "A green fruit" },
  { id: 13, name: "Lemon", description: "A yellow fruit" },
  { id: 14, name: "Lychee", description: "A red fruit" },
];
